from __future__ import annotations

"""Grammar model for the LL(1) Homi parser."""

EPSILON = "EPSILON"
ENDMARKER = "EOF"
START_SYMBOL = "program"


TERMINALS = {
    "ENTIDADE",
    "DISPOSITIVO",
    "AUTOMACAO",
    "MODO",
    "DESCRICAO",
    "GATILHOS",
    "CONDICOES",
    "ACOES",
    "QUANDO",
    "SE",
    "FACA",
    "ESPERE",
    "ESTADO",
    "SOL",
    "HORA",
    "HORARIO",
    "GATILHO",
    "PARA",
    "DE",
    "ATE",
    "ENTRE",
    "E",
    "EM",
    "IGUAL",
    "ANTES",
    "DEPOIS",
    "OFFSET",
    "LIGADO",
    "DESLIGADO",
    "ABERTA",
    "FECHADA",
    "ABERTO",
    "FECHADO",
    "ARMADO",
    "DESARMADO",
    "MOVIMENTO",
    "BATERIA",
    "VOLUME_FLUXO",
    "ACIMA",
    "ABAIXO",
    "QUALQUER",
    "TODOS",
    "ENTAO",
    "SENAO",
    "ESCOLHA",
    "CASO",
    "LIGAR",
    "DESLIGAR",
    "ALTERNAR",
    "ABRIR",
    "FECHAR",
    "SERVICO",
    "ALVO",
    "DADOS",
    "METADADOS",
    "TRUE",
    "FALSE",
    "SINGLE",
    "RESTART",
    "POR_DO_SOL",
    "NASCER_DO_SOL",
    "POR",
    "DIAS",
    "ID",
    "APELIDO",
    "HABILITADO",
    "DEVICE_ID",
    "ENTITY_ID",
    "IDENTIFIER",
    "DOTTED_ID",
    "STRING",
    "NUMBER",
    "DURATION",
    "LBRACE",
    "RBRACE",
    "LBRACKET",
    "RBRACKET",
    "LPAREN",
    "RPAREN",
    "COLON",
    "SEMICOLON",
    "COMMA",
    "ASSIGN",
    "EOF",
}


NON_TERMINALS = {
    "program",
    "top_level_list",
    "top_level_item",
    "entity_decl",
    "device_decl",
    "automation_decl",
    "mode",
    "automation_block",
    "description_section_opt",
    "description_section",
    "triggers_section_opt",
    "triggers_section",
    "trigger_list_opt",
    "trigger_stmt",
    "trigger_core",
    "state_trigger_core",
    "device_trigger_core",
    "sun_trigger_core",
    "sun_offset_opt",
    "time_trigger_core",
    "state_from_opt",
    "device_mode",
    "metric_name",
    "trigger_alias_opt",
    "trigger_id_opt",
    "trigger_for_opt",
    "weekday_opt",
    "weekday_list",
    "weekday_list_tail_opt",
    "weekday_literal",
    "sun_event",
    "comparison_op",
    "conditions_section_opt",
    "conditions_section",
    "condition_list_opt",
    "condition_stmt",
    "condition_entry_list_opt",
    "condition_entry",
    "condition_clause",
    "simple_condition",
    "logical_condition",
    "state_condition",
    "device_condition",
    "device_condition_mode",
    "trigger_condition",
    "time_condition",
    "time_condition_mode",
    "time_before_opt",
    "time_after_opt",
    "sun_condition",
    "sun_condition_mode",
    "sun_after_opt",
    "sun_before_opt",
    "condition_enabled_opt",
    "actions_section_opt",
    "actions_section",
    "action_list_opt",
    "action_stmt",
    "simple_action_stmt",
    "block_action_stmt",
    "action_command",
    "device_action",
    "device_verb",
    "service_action",
    "service_target_opt",
    "service_data_opt",
    "service_metadata_opt",
    "action_enabled_opt",
    "action_if_stmt",
    "action_else_opt",
    "action_block",
    "choose_stmt",
    "case_list_opt",
    "case_item",
    "target_block",
    "target_entry_list_opt",
    "target_entry",
    "target_entity_value",
    "target_device_value",
    "map_literal",
    "data_entry_list_opt",
    "data_entry",
    "map_key",
    "value",
    "atomic_value",
    "basic_value",
    "basic_or_list_value",
    "basic_list",
    "basic_list_tail_opt",
    "list_value",
    "list_tail_opt",
    "trigger_id_selector",
    "trigger_id_list",
    "trigger_id_list_tail_opt",
    "trigger_id_value",
    "entity_selector",
    "entity_list",
    "entity_list_tail_opt",
    "entity_ref",
    "device_subject",
    "device_subject_tail",
    "duration_value",
    "boolean_literal",
}


PRODUCTIONS: dict[str, list[list[str]]] = {
    "program": [["top_level_list", "EOF"]],
    "top_level_list": [["top_level_item", "top_level_list"], [EPSILON]],
    "top_level_item": [["entity_decl"], ["device_decl"], ["automation_decl"]],
    "entity_decl": [["ENTIDADE", "IDENTIFIER", "ASSIGN", "DOTTED_ID", "SEMICOLON"]],
    "device_decl": [
        [
            "DISPOSITIVO",
            "IDENTIFIER",
            "ASSIGN",
            "IDENTIFIER",
            "DEVICE_ID",
            "STRING",
            "ENTITY_ID",
            "STRING",
            "SEMICOLON",
        ]
    ],
    "automation_decl": [["AUTOMACAO", "STRING", "MODO", "mode", "automation_block"]],
    "mode": [["SINGLE"], ["RESTART"]],
    "automation_block": [
        [
            "LBRACE",
            "description_section_opt",
            "triggers_section_opt",
            "conditions_section_opt",
            "actions_section_opt",
            "RBRACE",
        ]
    ],
    "description_section_opt": [["description_section"], [EPSILON]],
    "description_section": [["DESCRICAO", "STRING", "SEMICOLON"]],
    "triggers_section_opt": [["triggers_section"], [EPSILON]],
    "triggers_section": [["GATILHOS", "LBRACE", "trigger_list_opt", "RBRACE"]],
    "trigger_list_opt": [["trigger_stmt", "trigger_list_opt"], [EPSILON]],
    "trigger_stmt": [["QUANDO", "trigger_core", "SEMICOLON"]],
    "trigger_core": [
        ["ESTADO", "state_trigger_core"],
        ["DISPOSITIVO", "device_trigger_core"],
        ["SOL", "sun_trigger_core"],
        ["HORA", "time_trigger_core"],
    ],
    "state_trigger_core": [
        [
            "entity_selector",
            "state_from_opt",
            "PARA",
            "basic_or_list_value",
            "trigger_alias_opt",
            "trigger_id_opt",
            "trigger_for_opt",
        ]
    ],
    "device_trigger_core": [
        [
            "device_subject",
            "device_mode",
            "trigger_alias_opt",
            "trigger_id_opt",
            "trigger_for_opt",
        ]
    ],
    "sun_trigger_core": [["sun_event", "sun_offset_opt", "trigger_alias_opt", "trigger_id_opt"]],
    "sun_offset_opt": [["OFFSET", "STRING"], [EPSILON]],
    "time_trigger_core": [["STRING", "weekday_opt", "trigger_alias_opt", "trigger_id_opt"]],
    "state_from_opt": [["DE", "basic_or_list_value"], [EPSILON]],
    "device_mode": [
        ["LIGADO"],
        ["DESLIGADO"],
        ["MOVIMENTO"],
        ["ABERTO"],
        ["FECHADO"],
        ["ABERTA"],
        ["FECHADA"],
        ["metric_name", "comparison_op", "basic_value"],
    ],
    "metric_name": [["IDENTIFIER"], ["BATERIA"], ["VOLUME_FLUXO"]],
    "trigger_alias_opt": [["APELIDO", "STRING"], [EPSILON]],
    "trigger_id_opt": [["ID", "STRING"], [EPSILON]],
    "trigger_for_opt": [["POR", "duration_value"], [EPSILON]],
    "weekday_opt": [["DIAS", "weekday_list"], [EPSILON]],
    "weekday_list": [["LBRACKET", "weekday_literal", "weekday_list_tail_opt", "RBRACKET"]],
    "weekday_list_tail_opt": [["COMMA", "weekday_literal", "weekday_list_tail_opt"], [EPSILON]],
    "weekday_literal": [
        ["IDENTIFIER"],
    ],
    "sun_event": [["NASCER_DO_SOL"], ["POR_DO_SOL"]],
    "comparison_op": [["ACIMA"], ["ABAIXO"], ["IGUAL"]],
    "conditions_section_opt": [["conditions_section"], [EPSILON]],
    "conditions_section": [["CONDICOES", "LBRACE", "condition_list_opt", "RBRACE"]],
    "condition_list_opt": [["condition_stmt", "condition_list_opt"], [EPSILON]],
    "condition_stmt": [["SE", "condition_clause", "condition_enabled_opt", "SEMICOLON"]],
    "condition_entry_list_opt": [["condition_entry", "condition_entry_list_opt"], [EPSILON]],
    "condition_entry": [["condition_clause", "condition_enabled_opt", "SEMICOLON"]],
    "condition_clause": [["simple_condition"], ["logical_condition"]],
    "simple_condition": [
        ["state_condition"],
        ["device_condition"],
        ["trigger_condition"],
        ["time_condition"],
        ["sun_condition"],
    ],
    "logical_condition": [
        ["QUALQUER", "LBRACE", "condition_entry_list_opt", "RBRACE"],
        ["TODOS", "LBRACE", "condition_entry_list_opt", "RBRACE"],
    ],
    "state_condition": [["ESTADO", "entity_ref", "IGUAL", "basic_or_list_value"]],
    "device_condition": [["DISPOSITIVO", "device_subject", "device_condition_mode"]],
    "device_condition_mode": [
        ["LIGADO"],
        ["DESLIGADO"],
        ["ABERTO"],
        ["FECHADO"],
        ["ARMADO"],
        ["DESARMADO"],
        ["metric_name", "comparison_op", "basic_value"],
    ],
    "trigger_condition": [["GATILHO", "EM", "trigger_id_selector"]],
    "time_condition": [["HORARIO", "time_condition_mode"]],
    "time_condition_mode": [
        ["ENTRE", "STRING", "E", "STRING"],
        ["DEPOIS", "STRING", "time_before_opt"],
        ["ANTES", "STRING", "time_after_opt"],
    ],
    "time_before_opt": [["ANTES", "STRING"], [EPSILON]],
    "time_after_opt": [["DEPOIS", "STRING"], [EPSILON]],
    "sun_condition": [["SOL", "sun_condition_mode"]],
    "sun_condition_mode": [
        ["ANTES", "sun_event", "sun_after_opt"],
        ["DEPOIS", "sun_event", "sun_before_opt"],
    ],
    "sun_after_opt": [["DEPOIS", "sun_event"], [EPSILON]],
    "sun_before_opt": [["ANTES", "sun_event"], [EPSILON]],
    "condition_enabled_opt": [["HABILITADO", "boolean_literal"], [EPSILON]],
    "actions_section_opt": [["actions_section"], [EPSILON]],
    "actions_section": [["ACOES", "LBRACE", "action_list_opt", "RBRACE"]],
    "action_list_opt": [["action_stmt", "action_list_opt"], [EPSILON]],
    "action_stmt": [["simple_action_stmt"], ["block_action_stmt"]],
    "simple_action_stmt": [
        ["FACA", "action_command", "action_enabled_opt", "SEMICOLON"],
        ["ESPERE", "duration_value", "action_enabled_opt", "SEMICOLON"],
    ],
    "block_action_stmt": [["action_if_stmt", "action_enabled_opt"], ["choose_stmt", "action_enabled_opt"]],
    "action_command": [["device_action"], ["service_action"]],
    "device_action": [["device_verb", "device_subject"]],
    "device_verb": [["LIGAR"], ["DESLIGAR"], ["ALTERNAR"], ["ABRIR"], ["FECHAR"]],
    "service_action": [["SERVICO", "DOTTED_ID", "service_target_opt", "service_data_opt", "service_metadata_opt"]],
    "service_target_opt": [["ALVO", "target_block"], [EPSILON]],
    "service_data_opt": [["DADOS", "map_literal"], [EPSILON]],
    "service_metadata_opt": [["METADADOS", "map_literal"], [EPSILON]],
    "action_enabled_opt": [["HABILITADO", "boolean_literal"], [EPSILON]],
    "action_if_stmt": [["SE", "condition_clause", "ENTAO", "action_block", "action_else_opt"]],
    "action_else_opt": [["SENAO", "action_block"], [EPSILON]],
    "action_block": [["LBRACE", "action_list_opt", "RBRACE"]],
    "choose_stmt": [["ESCOLHA", "LBRACE", "case_list_opt", "RBRACE"]],
    "case_list_opt": [["case_item", "case_list_opt"], [EPSILON]],
    "case_item": [["CASO", "condition_clause", "action_block"]],
    "target_block": [["LBRACE", "target_entry_list_opt", "RBRACE"]],
    "target_entry_list_opt": [["target_entry", "target_entry_list_opt"], [EPSILON]],
    "target_entry": [
        ["ENTITY_ID", "COLON", "target_entity_value", "SEMICOLON"],
        ["DEVICE_ID", "COLON", "target_device_value", "SEMICOLON"],
    ],
    "target_entity_value": [["entity_ref"], ["entity_list"]],
    "target_device_value": [["STRING"], ["basic_list"]],
    "map_literal": [["LBRACE", "data_entry_list_opt", "RBRACE"]],
    "data_entry_list_opt": [["data_entry", "data_entry_list_opt"], [EPSILON]],
    "data_entry": [["map_key", "COLON", "value", "SEMICOLON"]],
    "map_key": [["IDENTIFIER"], ["DEVICE_ID"], ["ENTITY_ID"], ["METADADOS"]],
    "value": [["atomic_value"], ["list_value"], ["map_literal"]],
    "atomic_value": [["basic_value"], ["duration_value"]],
    "basic_value": [
        ["STRING"],
        ["NUMBER"],
        ["boolean_literal"],
        ["IDENTIFIER"],
        ["DOTTED_ID"],
    ],
    "basic_or_list_value": [["basic_value"], ["basic_list"]],
    "basic_list": [["LBRACKET", "basic_value", "basic_list_tail_opt", "RBRACKET"]],
    "basic_list_tail_opt": [["COMMA", "basic_value", "basic_list_tail_opt"], [EPSILON]],
    "list_value": [["LBRACKET", "value", "list_tail_opt", "RBRACKET"]],
    "list_tail_opt": [["COMMA", "value", "list_tail_opt"], [EPSILON]],
    "trigger_id_selector": [["trigger_id_value"], ["trigger_id_list"]],
    "trigger_id_list": [["LBRACKET", "trigger_id_value", "trigger_id_list_tail_opt", "RBRACKET"]],
    "trigger_id_list_tail_opt": [["COMMA", "trigger_id_value", "trigger_id_list_tail_opt"], [EPSILON]],
    "trigger_id_value": [["STRING"], ["IDENTIFIER"]],
    "entity_selector": [["entity_ref"], ["entity_list"]],
    "entity_list": [["LBRACKET", "entity_ref", "entity_list_tail_opt", "RBRACKET"]],
    "entity_list_tail_opt": [["COMMA", "entity_ref", "entity_list_tail_opt"], [EPSILON]],
    "entity_ref": [["DOTTED_ID"], ["IDENTIFIER"]],
    "device_subject": [["IDENTIFIER", "device_subject_tail"]],
    "device_subject_tail": [["DEVICE_ID", "STRING", "ENTITY_ID", "STRING"], [EPSILON]],
    "duration_value": [["DURATION"]],
    "boolean_literal": [["TRUE"], ["FALSE"]],
}
