- alias: Sala - porta de entrada
  description: ''
  triggers:
  - trigger: device
    domain: binary_sensor
    device_id: 5ab340c52c9995f0bafbc6c0dc79812e
    entity_id: b729bfc5dc7003d3bca5d64247f8dfc6
    type: opened
    id: Aberta
  - trigger: device
    domain: binary_sensor
    device_id: 5ab340c52c9995f0bafbc6c0dc79812e
    entity_id: b729bfc5dc7003d3bca5d64247f8dfc6
    type: opened
    id: Aberta 1 min
    for:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - trigger: device
    domain: binary_sensor
    device_id: 5ab340c52c9995f0bafbc6c0dc79812e
    entity_id: b729bfc5dc7003d3bca5d64247f8dfc6
    type: not_opened
    id: Fechada
  conditions: []
  actions:
  - if:
    - condition: and
      conditions:
      - condition: trigger
        id: Aberta
      - condition: state
        entity_id: switch.luzes_da_sala
        state: 'off'
      - condition: device
        domain: media_player
        device_id: 9effd46c0c669c81be568b6baf21a14c
        entity_id: eea259ec8e8a95d09dd5c7d8619d1658
        type: is_off
      - condition: device
        domain: media_player
        device_id: d9c64e91476cb5a39d1fdf508673f900
        entity_id: ccc6d60a59506b4beb48870f9263604a
        type: is_off
    then:
    - type: turn_on
      device_id: 5f9afdf1309a0b93f968874d8987f9ff
      entity_id: 67a209bb0d8363e1f2526bdbba20ba71
      domain: light
    - action: notify.mobile_app_zfold4
      data:
        message: Porta aberta e luz de entrada ligada!
  - if:
    - condition: trigger
      id: Aberta 1 min
    then:
    - action: notify.send_message
      target:
        entity_id:
        - notify.echo_show_8_speak
        - notify.music_frame_alexa_speak
      data:
        message: Porta aberta ha mais de 1 minuto!
    - action: notify.mobile_app_zfold4
      data:
        message: Porta aberta por 1 minuto!
  mode: single
